# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('english_translation', models.TextField()),
                ('spanish_translation', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
