# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Similar')], default='N', max_length=1, verbose_name='Corrected'),
        ),
    ]
